### ISSUE TITLE
Cannot set created_by_id 

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad-api-client-php#1]
I would like to set the ``created_by_id`` value with the api to assign a message to an user.

```php
$ticket->setValue("article", array(
    "subject"=>"Test subject",
    "body"=>"test message",
    "created_by_id"=>$userId, // DOESNT WORK
    "updated_by_id"=>$userId // DOESNT WORK
));
```

**Comment by martini** [comment]
Hello again! :)

The created_by_id and updated_by_id is set by the session (taken from authenticated user).

It's not possible to overwrite, for security reasons.

Let me know what your use case is. :)

 -Martin

**Comment by MDXDave** [comment]
I need to create a ticket over the api which can be answered in the zammad interface via email 😄

**Comment by martini** [comment]
>I need to create a ticket over the api which can be answered in the zammad interface via email 😄

And you need to create the ticket as "customer" to have the correct recipients on email reply via Zammad web interface?

**Comment by MDXDave** [comment]
If there is any other possibility, its not that important. But i don't know how to create a ticket, which can be answered over zammad.

**Comment by MDXDave** [comment]
Not possible? 😞

**Comment by martini** [comment]
@MDXDave , sorry for the delay. 

Currently the updated_by_id is set by the session for the authenticated user.

> I need to create a ticket over the api which can be answered in the zammad interface via email 😄

Can you try the following:

```
$ticket->setValue("article", array(
    "subject"=>"Test subject",
    "body"=>"test message",
    "sender"=>"Customer", 
    "to" => "Name of Group",
));
```

Will produce this behaviour:

<img width="715" alt="screen shot 2017-02-11 at 20 57 37" src="https://cloud.githubusercontent.com/assets/110226/22856974/c8f2e408-f09c-11e6-986b-9834e29f8919.png">


Background info: In future we will extend the article model with origin_by_id to differ between article creator and who was the initiator of the article. But until this you need to set the sender to "Customer" and add the to field.

Feedback is welcome!

**Comment by vmendez-es** [comment]
Hello @martini, I'm trying to create a ticket through the API using the information you kindly suggested to @MDXDave. Unfortunately, I've not been able to to so using that information.

Doing a little bit of research I found that the desired behavior can be achieved adding the following fields
"'from' => $user_email" and "'type' => 'email'"

Here is the code based in the example for the creation of a ticket:

```php
$ticket_text = 'API test ticket';
$ticket_data = [
    'group_id'    => 1,
    'priority_id' => 1,
    'state_id'    => 1,
    'title'       => $ticket_text,
    'customer_id' => $user_id,
    'article'     => [
        'subject' => $ticket_text,
        'body'    => $ticket_text,
        'sender'  => 'Customer',
        'from'    => $email_address,
    	'to'      => 'Users',
    	'type'    => 'email',
    ],
];
```
Any suggestion is welcome!

**Comment by rolfschmidt** [comment]
Hi @MDXDave,
if you want to create a article on behalf for a specific customer you could create a phone article with the attribute origin_by_id (only possible for sender **customer** and type **phone**).

https://docs.zammad.org/en/latest/api-ticket-article.html#create

```
    'group_id'    => 1,
    'priority_id' => 1,
    'state_id'    => 1,
    'title'       => $ticket_text,
    'customer_id' => $user_id,
    'article'     => [
        'subject'      => $ticket_text,
        'body'         => $ticket_text,
        'sender'       => 'Customer',
        'type'         => 'phone',
        'origin_by_id' => $user_id,
    ],
```

Related: https://github.com/zammad/zammad/issues/206

Changes are currently available in the develop branch. I hope this will solve your problems creating articles for your customer. If not you can reopen the issue with more information if you like to.

-Rolf
