### ISSUE TITLE
Add support for 'X-On-Behalf-Of'-Header.

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad-api-client-php#11]
Hi,
there is a new feature which should get supported in the zammad apis:

issue:
https://github.com/zammad/zammad/issues/1805

documentation:
https://docs.zammad.org/en/latest/api-intro.html#example-curl-request-on-behalf-of-a-different-user

Best regards,
Rolf

**Comment by jepf** [comment]
Done: bf76748f7ec88be6d2d41cce5dd3effa919bcb17
