### ISSUE TITLE
RuntimteException in Client.php

### ISSUE THREAD

**Issue by pebosi** [zammad/zammad-api-client-php#13]
> RuntimeException: Unable to create HTTP client request. in ZammadAPIClient\Client->request() (Zeile 87 in ../vendor/zammad/zammad-api-client-php/src/Client.php).

Using Zammad Client in an Drupal 8 enviroment.
Zammad 2.4-dev
Zammad Client 1.2
PHP 7.0

**Comment by jepf** [comment]
Hi @pebosi,

could you please provide a code example that causes the error?

**Comment by pebosi** [comment]
```
use ZammadAPIClient\Client;
use ZammadAPIClient\ResourceType;

$client = new Client(['url' => 'http://local', 'http_token' => 'xxxxx']);
$customer = $client->resource( ResourceType::USER );

$customer->setValues([
'login' => 'mail@local.com',
'email' => 'mail@local.com',
'firstname' => 'TestX',
'lastname' => 'TestY',
'phone' => '+49123456789',
'city' => 'City',
'street' => 'Street 1',
'zip' => '12345',
'country' => '',
]);
$customer->save();

```

But i already found the problem. It happens when passing empty values like "country". Filter out empty values in my code fixes this.

**Comment by jepf** [comment]
Hi @pebosi 

unfortunately I cannot reproduce the runtime exception with your code example, it creates the user without errors.

I would be glad if you report further issues with this if you happen to notice them.
