### ISSUE TITLE
Search for specific fields not working

### ISSUE THREAD

**Issue by jschurse** [zammad/zammad-api-client-php#2]
Hey,
in your documentation you write, that an field specific search is possible:

```
// Field specific search
$tickets = $client->resource( ResourceType::TICKET )->search('title:My Title');
```

unfortunately zammad always returns an empty result object if I try to search in fields.
Is this feature not yet implemented in the API?

Best regards,
J. Schurse

**Comment by martini** [comment]
Hi @jschurse 

sorry for the long delay. We got not github notifications. :-o

Anyway, your search should work. To use certain queries like you want you need to have elasticsearch configured at Zammad backend. Do you have elasticsearch installed/configured?

Second question. Can you search for "title:My Title" in the Zammad UI, did you find something there?

 -Martin

**Comment by jschurse** [comment]
Hey,

Elasticsearch was not running. After installing and configuring it everything is working fine.
Thanks for that hint!

Best regards,

J. Schurse

**Comment by martini** [comment]
Thanks for feedback! ❤️
