### ISSUE TITLE
Resource->all() method name is missleading

### ISSUE THREAD

**Issue by obuchmann** [zammad/zammad-api-client-php#22]
$resource->all() does not fetch more then the default limit of 500.

See: https://github.com/zammad/zammad/issues/768

we should really fetch all with iterating over pagination or set objects_per_page to default 500.

**Comment by jepf** [comment]
Hi @obuchmann 
Version 1.3.2 now supports retrieval of all objects, regardless of server-side limit. This is possible for all() as well as search().

Please let me know if it works for you.
