### ISSUE TITLE
Support of CSV Import via API Client

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad-api-client-php#24]
Hi all

Does the api client support the file import to users / organizations / text_modules or should we "implement" this post request by ourselves?

eg. https://github.com/zammad/zammad/blob/a1da3a27f98a0146838befe366674ed895b5503c/app/controllers/users_controller.rb#L1008

BR wucherpfennig

**Comment by jepf** [comment]
@wucherpfennig 
This has been added to the client in version 1.4.0.

There is now an import method:

```php
use ZammadAPIClient\ResourceType;

$text_modules_csv_string = file_get_contents('text_modules.csv');

$client->resource( ResourceType::TEXT_MODULE )->import($text_modules_csv_string);
```

**Comment by wucherpfennig** [comment]
THANK YOU!

**Comment by wucherpfennig** [comment]
@jepf I noticed that other resources support import too: https://github.com/zammad/zammad/blob/5f3c793f373e3f508395893801ba8064303da2ae/app/controllers/organizations_controller.rb#L339 

After checking the clients definition I assume that this API client supports import currently only with text_modules. Would you mind to update the client in order to support organizations and users too?
