### ISSUE TITLE
Search for user – empty return

### ISSUE THREAD

**Issue by heini23** [zammad/zammad-api-client-php#25]
If we use the api to search for an user, we always get an empty return. Everything else – like searching for tickets -  works well.

Example:
https://XXX.zammad.com/api/v1/users/search?query=Max&token=XXX
(the token has all available rights)

We have a user “Max Mustermann”, therefore we would assume to get his user profile as a return. But the return is empty.

Header Return:

> 1.	Status Code: 200 OK
> 2.	cache-control: max-age=0, private, must-revalidate
> 3.	content-encoding: gzip
> 4.	content-type: application/json; charset=utf-8
> 5.	csrf-token: XXX
> 6.	date: Wed, 27 Nov 2019 11:41:51 GMT
> 7.	etag: W/"XXX"
> 8.	referrer-policy: strict-origin-when-cross-origin
> 9.	server: nginx
> 10.	strict-transport-security: max-age=63072000
> 11.	x-content-type-options: nosniff
> 12.	x-download-options: noopen
> 13.	x-firefox-spdy: h2
> 14.	x-frame-options: DENY
> 15.	x-permitted-cross-domain-policies: none
> 16.	x-request-id: 6137ba5a-b0a0-40c0-ab90-d21e83f9bb77
> 17.	x-runtime: 0.026655
> 18.	x-xss-protection: 1; mode=block

**Comment by MrGeneration** [comment]
As addition, this was the used code:

```
require '../../vendor/autoload.php';

$zammad_api_client_config = ['url' =>
'https://XXX.zammad.com','username'; => 'xxx','password' => 'xxx',
];

use ZammadAPIClient\Client;
use ZammadAPIClient\ResourceType;

$client = new Client($zammad_api_client_config);
$users = $client->resource( ResourceType::USER
)->search("mustermann@musterfirma.de");
print 'Found ' . count($users) . ' user';
```

I can verify this with my very limited skillset regarding the steps required to "make this run".

**Comment by jepf** [comment]
@heini23 
Please try the following code (please pay attention to the path to your autoload.php file and adjust it according to your needs):

```php
require __DIR__ . '/../vendor/autoload.php';

use ZammadAPIClient\Client;
use ZammadAPIClient\ResourceType;

$zammad_api_client_config = [
    'url' => 'https://XXX.zammad.com',
    'username' => 'xxx',
    'password' => 'xxx',
];

$client = new Client($zammad_api_client_config);

$users = $client->resource( ResourceType::USER )->search("Max");
if ( !is_array($users) ) {
    print $users->getError() . "\n";
    exit(1);
}

foreach ( $users as $user ) {
    print_r( $user->getValues() );
}
```

Did I understand it correctly that the problem only exists with the PHP client or does it also not work with a direct call of the link [https://xxx.zammad.com/api/v1/users/search?query=Max&token=XXX](url)

**Comment by heini23** [comment]
Originally neither the direct call or the posted script worked.
I just tried it again and both works great now.

I don’t know if you fixed the bug or if the system simply had a bad day – but everything works great now :D

**Comment by heini23** [comment]
**REOPEN**

sadly the bug is back.
As described in the first post the search doesn’t work (neither with the PHP Script or with the direct call of the link)


It worked for the past 2 weeks and now it doesn’t work anymore. The result of every search is empty. Sadly we didn’t log the errors, so I cant specify an exact date :(

**Comment by thorsteneckel** [comment]
Hi @heini23 - you are using one of the hosted instances over at zammad.com, right? Would you mind writing an email to support at zammad dot com and referring to this issue and me? Please add the name of your hosted instance and what your are searching for as well. I'll have a look 👍

**Comment by ma2t** [comment]
Hello here,

I have exactly the same issue than @MrGeneration and @heini23.

If I follow his example:

- The client is calling "/api/v1/users/search?expand=1&query=mustermann%40musterfirma.de
- Zammad API return: []

But, if I add "&sort_by=created_at" to the URL called by the client, Zammad return the user.

Tested with self-hosted Zammad  3.2 and 3.3.

To temporary fix this issue, I added the following line into src/Resource/AbstractResource.php search function:
$url_parameters['sort_by'] = 'created_at';

Maybe adding a param to this function to sort may be a good idea?

Thank you @thorsteneckel for your great work on Zammad ❤️.
