### ISSUE TITLE
Add CSV Import to supported Resources

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad-api-client-php#28]
Addition to https://github.com/zammad/zammad-api-client-php/issues/24

@jepf I noticed that other resources support import too, see example: https://github.com/zammad/zammad/blob/5f3c793f373e3f508395893801ba8064303da2ae/app/controllers/organizations_controller.rb#L339 

After checking the clients definition I assume that this API client supports import currently only with text_modules. Would you mind to update the client in order to support organizations and users too?

**Comment by jepf** [comment]
@wucherpfennig 
Thank you for your request. I will look into this (probably this week).

**Comment by jepf** [comment]
@wucherpfennig 
The API client now supports CSV import for users and organizations. The git tag is "1.5.0". Note that this version is currently not available via packagist/composer. I have to clarify permissions for this first. But you can fetch it from GitHub.

**Comment by wucherpfennig** [comment]
Dear @jepf 
Thank you so much! This will definitively help with my sync issues (2 Installations with each around 10-15K Organisations + 10-20k Users).
When do you think you will have sorted out the composer situation?
BR wucherpfennig

**Comment by jepf** [comment]
@wucherpfennig 
It's now also available via packagist/composer.
