### ISSUE TITLE
Fetching Knowledge Base entries

### ISSUE THREAD

**Issue by simplexx** [zammad/zammad-api-client-php#29]
Is it possible to fetch Knowledge Base entries with this API? Cheers

**Comment by MrGeneration** [comment]
No, this is currently out of scope of this API-Client.  
You can find all available scopes of this Client libary here: https://github.com/zammad/zammad-api-client-php/blob/master/README.md#available-resource-types-and-their-access-methods

Knowledgebase isn‘t listed entirely.

**Comment by wucherpfennig** [comment]
Well but it would help if it was ;-)

**Comment by obstschale** [comment]
👍 For This feature. I could use knowledge base ressources as well in the REST API. Especially for migrating from an old KB.
