### ISSUE TITLE
Problem on searching tickets

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad-api-client-php#3]
Hi!

If i use the following:
`->resource(ResourceType::TICKET)->search("test");`
the Client finds several Tickets.
See:
`  0 => Ticket {#448 ▼
    -client: Client {#648 ▶}
    -remote_data: array:47 [▼
      "id" => 1267
      "group_id" => 16
      "priority_id" => 2
      "state_id" => 1
      "organization_id" => 2
      "number" => "941267"
      "title" => "test"
      "owner_id" => 1
      "customer_id" => 53
      "note" => null
      "first_response_at" => null
      "first_response_escalation_at" => null
      "first_response_in_min" => null
      "first_response_diff_in_min" => null
      "close_at" => null
      "close_escalation_at" => null
      "close_in_min" => null
      "close_diff_in_min" => null
      "update_escalation_at" => null
      "update_in_min" => null
      "update_diff_in_min" => `null`

But if i try to search using the field-syntax it just returns an empty array.
For example: 
`->resource(ResourceType::TICKET)->search("title:test");`

I'm using Zammad 1.3.0. (PHP 7)

Any idea? :-)

Thx for your time!

Best Regards,
David

**Comment by martini** [comment]
Hi @ThePatzen 

do you use Zammad with Elasticsearch? Or only with SQL backend?

 -Martin

**Comment by ThePatzen** [comment]
Hi @martini 

thank you for your hint! Somehow missed to set up Elasticsearch!

- David

**Comment by martini** [comment]
Thank for feedback.
