### ISSUE TITLE
Zammad 3.5/3.4 API incompatibilities

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad-api-client-php#31]
Hi @jepf - we had to change the following API endpoints because of a security issue:

- `GET /api/v1/tags/add` -> `POST /api/v1/tags/add`
- `GET /api/v1/tags/remove` -> `DELETE /api/v1/tags/add`
- `GET /api/v1/links/add` -> `POST /api/v1/links/add`
- `GET /api/v1/links/remove` -> `DELETE /api/v1/links/add`
- `GET /api/v1/ticket_merge/:id_source/:id_target` -> `PUT /api/v1/ticket_merge/:id_source/:id_target`

Can you please check this and apply the required changes?

**Comment by jepf** [comment]
This has been fixed/changed in client version 1.6.0. It needs Zammad >= 3.4 from now on.
