### ISSUE TITLE
Return value of ZammadAPIClient\HTTPClient::request() must be an instance of Psr\Http\Message\ResponseInterface, null returned

### ISSUE THREAD

**Issue by Joker2711** [zammad/zammad-api-client-php#36]
Hello,

I always get a TypeError when I send my request to the Zammad API.
I just send a simple GET request to read the Tickets

![TypeError](https://user-images.githubusercontent.com/28525095/99794267-31db2b80-2b2a-11eb-817a-1b2c0ea3e120.png)

**Comment by Wallace911** [comment]
the same error show to me with a request of user. But if I write the request at the api in my browser the request have found with a response

**Comment by ouun** [comment]
Same here. Issue seems to come from HTTPClient.php if more than one authentification is set. Try to set either username/password, http_token or oauth2_token.

**Comment by mgruner** [comment]
@Joker2711 @Wallace911 can you please provide a sample request that causes this failure (with anonymized token/password)? Does it work correctly if you send only one authentication method as described by @ouun?

**Comment by mgruner** [comment]
I'll close this for now, please feel free to follow up with more info.
