### ISSUE TITLE
Link one ticket with an other

### ISSUE THREAD

**Issue by mrohnstock** [zammad/zammad-api-client-php#39]
(excuse me, if this is the wrong place to ask for such things, feel free to close the ticket if this isn't right here)

Hi, I'm already working with this client since a few month, but am missing one feature:

Is there a way to see linked tickets and link one ticket with an other through API?
Looks like this is only possible through zammad directly?  I can't find anything in the [docs](https://docs.zammad.org/en/latest/api/ticket.html), too, so I guess this isn't implemented in zammad.

I'm talking about this feature on right menu in zammad:

![image](https://user-images.githubusercontent.com/823072/114854145-ce0d1400-9de4-11eb-8e5a-5ce0f849709a.png)

If I link an ticket with an other, there is no extra info in the object received from the API in any of these tickets.

Thanks!

**Comment by thorsteneckel** [comment]
Hi @mrohnstock - you are right. The API clients currently don't support the (generic) link-ing endpoints of the Zammad REST API. What you can do is to quert the REST API manually:

```
GET /api/v1/links?link_object=Ticket&link_object_value=*ticket_id*

POST /api/v1/links/add?link_type=normal&link_object_source=Ticket&link_object_source_number=*source_ticket_number*&link_object_target=Ticket&link_object_target_value=*target_ticket_id*
```

Please note the `ticket_NUMBER` and `ticket_ID` difference for the `/links/add` endpoint.

A contribution to the API client for supporting this functionality is highly welcome 👋

**Comment by mgruner** [comment]
@mrohnstock please feel free to take feature requests to https://community.zammad.org/. Thank you!
