### ISSUE TITLE
Ticket Attachment

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad-api-client-php#4]
Hi!

I have a question:
How do i create a TicketAttachment using your Api-Client?

Thanks for your time!
- David

**Comment by martini** [comment]
Just a short note, we improved the attachment handling via REST in upcoming next version.

See also:
https://github.com/zammad/zammad-documentation/blob/master/api-ticket-article.rst

Improvement need to be implemented in the php api client. @jepf can you put it on your stack?

**Comment by martini** [comment]
Update: @jepf implemented the attachment support for Zammad 1.4 and higher to the api client.

Here is an example how to create an article with attachments.

https://github.com/zammad/zammad-api-client-php/blob/master/test/ZammadAPIClient/Resource/TicketArticleTest.php#L33

Note: You also can create articles with html and inline images, see https://github.com/zammad/zammad-documentation/blob/master/api-ticket-article.rst -> "If you want to add inline images, just use data uris in html markup".
