### ISSUE TITLE
Adding Contacts / Unable to create http client request

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad-api-client-php#40]
Dear all

Whilst creating new contacts via the API we are getting constantly the error:

```
Unable to create http client request
```

https://github.com/zammad/zammad-api-client-php/blob/14099928589c1a9e9b3fafcf596241ddff666143/src/Client.php#L79-82

During development we cannot reproduce this kind of error. Does anybody have an idea why this error is thrown?

BR wucherpfennig

**Comment by wucherpfennig** [comment]
I have updated the title in order to potentially narrow down this issue. Creating textmodules and organisations works without any issues. This error appears only while creating customer contacts.

**Comment by MrGeneration** [comment]
Please provide the payload or script you're trying to use against the API.

**Comment by wucherpfennig** [comment]
After further investigation I notice that the issue appears only while creating contacts. In addition saw (from the "source" side) that creating the first entity is not an issue but the second yields in this error. 

The payload used looks like this:

```
Array
(
    [login] => someUserNameWithoutSpecialCars
    [firstname] => SomeFirstName
    [lastname] => SomeName
    [email] => frank@someemail.ch
    [web] =>
    [phone] => +41123123
    [fax] =>
    [mobile] => +41123123
    [department] =>
    [street] => Street 116
    [zip] => 9999
    [city] => City
    [country] => Country
    [address] => Street 116
9999 Some Place
Country
    [vip] =>
    [verified] => 1
    [active] => 1
    [note] => Direktion/Directeur / Spricht CH/Geschäftsführung
    [roles] => Customer
    [organization_id] => 1189
    [cus_crm_number] => XYZ15469
)
```

The script used (which works fine for textmodules and organisations) looks like:

```
    protected function getApiClient($tenant): Client
    {
        $credentials = $this->getCredentials($tenant);
        return new Client($credentials);
    }

    public function createEntity(string $tenantMachineName, $entity)
    {
        $result = array();
        /* @var $resource AbstractResource */
        $resource = $this->getApiClient($tenantMachineName)->resource($this->getResourceType());
        $entityReturned = $resource->setValues($entity)->save();
        if ($entityReturned->hasError() !== TRUE) {
            $result = $entityReturned->getValues();
        } else {
            $error = sprintf(
                "message: %s\nentity: %s",
                $entityReturned->getError(),
                print_r($entity, TRUE)
            );
            throw new Exception($error);
        }
        return $result;
    }
```

**Comment by wucherpfennig** [comment]
As mentioned the issue was tied to the timeout. Therefore I close this ticket.
