### ISSUE TITLE
Exception in src/Client.php at line 7

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad-api-client-php#5]
Hi!

I get an error in the Client.php at line 7.

- at Client ->request ('GET', 'users?expand=1', array('expand' => true)) 
 in vendor/zammad/zammad-api-client-php/src/Client.php at line 94   + 
- at Client ->get ('users', array('expand' => true)) 
 in vendor/zammad/zammad-api-client-php/src/Resource/AbstractResource.php at line 318   + 

Somehow i don't get an response from the HTTP Client?

Greeds from Austria!
- David

**Comment by jepf** [comment]
Hi David,

could you please provide some of the code you use to access Zammad?
Which authentication method do you use (username/password or HTTP token)?

Regards,
   Jens
