### ISSUE TITLE
Support PHP 8.x

### ISSUE THREAD

**Issue by Blackskyliner** [zammad/zammad-api-client-php#54]
Currently the library only supports PHP 7.4
As of 28 November 2022 that version is EOL.

To make the Library available to new Projects using PHP 8.x at least a bump of the version within the composer.json PHP Version constraint would be needed.

Also the Github Workflow would need adjustments, I guess, to let all tests run within the max. supported version (PHP8.2 would be a good target at the moment as its the most recent stable version) but also with the min. supported Version (PHP 7.2) -- Question would be if a BC Breaking Major/Minor Version bump should be done and dropping PHP 7.x support all together enabling the Library to move forward with modern PHP Features. (But strongly optional, it would already be great if it installs on PHP8.x and is usable in modern/new applications)

**Comment by mgruner** [comment]
Hi @Blackskyliner, 
can you explain a bit more about what should be changed in the version constraint? I read `php: >=7.2` as allowing for PHP 8 and higher as well.
I'm working on adding PHP version matrix testing for GitHub CI.

**Comment by Blackskyliner** [comment]
Your dependencies also need to support PHP8.x but the used versions are too old (guzzle from 2017 and also phpunit 7.x) and thus only specify 7.x compatibility because they use the ^ constraint operator which won't include go major versions upgrades.

Most of the time its better to explicitly state up to which version a library is supported. Specifyng >= for the min tested version and <= for the max tested version could be a viable option. It also makes it easier to see if the author knows and thought about compatibility with that specific version(-range) of PHP. Which also makes platform (eg. from 7.4 to 8.0) upgrades more easy, as a simple composer update will just tell which libs are not working with the current php platform version used, instead of exploding while using because of PHP deprecations or whatever.

**Comment by mgruner** [comment]
Can you please check again after [54b21bc](https://github.com/zammad/zammad-api-client-php/commit/54b21bc38ffa9d92acdd3783d52f658b837a14bf). The phpunit restriction was loosened, and the testing matrix is green from PHP 7.2 to 8.2. Please feel free to reopen with more details.
