### ISSUE TITLE
Commercial use of this library under GPL with zammad.com Hosting

### ISSUE THREAD

**Issue by jansgescheit** [zammad/zammad-api-client-php#55]
If I use Zammad with the "Professional" subscription and want to use this API client I have a conflict with the commercial use of this library under GPL. Does Zammad have a solution for customers using Zammad commercially via the hosting variant?

**Comment by jansgescheit** [comment]
My problem is the GPL in a closed software. My understanding is that a project that uses code that is under the GPL, or is derived from such code, must also be released under the GPL.

**Comment by mgruner** [comment]
Hi @jansgescheit thank you for your patience. We decided to dual license the API clients, adding the MIT as a permissive license that should support your use case.
