### ISSUE TITLE
PHP fatal error occassionally

### ISSUE THREAD

**Issue by ktb92677** [zammad/zammad-api-client-php#7]
Hi! So occasionally when I am running a script I get the following error message:

PHP Fatal error: Call to a member function getStatusCode() on null in ../zammad/vendor/zammad/zammad-api-client-php/src/Client.php on line 72

The strange thing is that this only occurs sometimes and does not occur everytime I run the same exact script. Do you know what is going on here?

**Comment by monotek** [comment]
I guess connection problem to the server.

**Comment by ktb92677** [comment]
So how can I resolve this?

**Comment by ktb92677** [comment]
And why does it only happen occasionally?

**Comment by ktb92677** [comment]
Can I disable this call?

**Comment by thorsteneckel** [comment]
@jepf - could you please take a look at this?

**Comment by jepf** [comment]
Hi @ktb92677 

is it possible for you to provide (part of) your code which leads to the error?

**Comment by ktb92677** [comment]
Sure, the following script works about 85% of the time but will for some reason fail on occasion (with the same exact parameters passed in. I hope it's not my set up that is causing this issue:

```
<?php

require_once 'vendor/autoload.php';

use ZammadAPIClient\Client;
use ZammadAPIClient\ResourceType;

$client = new Client([
    'url'           => 'http://host', # URL to your Zammad installation
    'username'      => $argv[1],  # Username to use for authentication
    'password'      => $argv[2],           # Password to use for authentication
]);

$ticket = $client->resource( ResourceType::TICKET )->get($argv[3]); #ticket ID

$ticket1 = $client->resource( ResourceType::TICKET_ARTICLE )->get($ticket->getValues()['article_ids'][$argv[4]]); #article ID... starts from 0

if ($ticket1->getValues()['type'] != "email" || $ticket1->getValues()['sender'] != "System") {
	print("\"".$ticket1->getValues()['body']."\"".$ticket1->getValues()['from']);
	
	if ($ticket1->getValues()['created_by'] == $argv[1] && strpos($ticket1->getValues()['from'], $argv[1]) == false) {
		print(" <".$ticket1->getValues()['created_by'].">");
	}
	print("\n");
}

function exitOnError($object) {
    if ( $object->hasError() ) {
        print $object->getError() . "\n";
        exit(1);
    }
}

?>

```

**Comment by jepf** [comment]
Hi @ktb92677 

Unfortunately I could not reproduce your problem yet, but I added a debug option to the PHP client:

```php
$client = new Client([
    'url'           => 'http://host', # URL to your Zammad installation
    'username'      => $argv[1],  # Username to use for authentication
    'password'      => $argv[2],           # Password to use for authentication
    'debug'           => true,
]);
```

Could you please update your Zammad client and test it with this debug option? Maybe there's some output that shows your problem.
