### ISSUE TITLE
Get User ID from email address

### ISSUE THREAD

**Issue by vmendez-es** [zammad/zammad-api-client-php#9]
Hello! First of all, congratulations for your job, it's very useful to me :)

I'm intending to get the user ID from its mail, but I'm facing a private array. Here is the code:

`$email_address = 'api_test@example.com';
$user_data = [
    'login' => $email_address,
    'email' => $email_address,
];
$user = $client->resource( ResourceType::USER );
$user->setValues($user_data);
$user->save();
$user_id = $user->getID();

if (is_null($user_id)){
	$error = $user->getError();
	var_dump($error);
	if($error == 'Object already exists!'){
		$user_by_email= $client->resource( ResourceType::USER )->search($email_address);
		$user_by_email->getValue('id');
	}
}`

With this code I'm getting this error:

`PHP Fatal error:  Uncaught Error: Call to a member function getValue() on array in /home/xxxxxx/git_projects/xxxxx/zammad test/zammadusers.php:30`

So I tried accessing the user array by `var_dump($user_by_email);` on the last line of the code. The problem is that I am encountering "private"arrays. **How can I get the user ID**? 

`array(1) {
  [0]=>
  object(ZammadAPIClient\Resource\User)#29 (4) {
    ["client":"ZammadAPIClient\Resource\AbstractResource":private]=>
    object(ZammadAPIClient\Client)#2 (2) {
     ...........
     }
    ["remote_data":"ZammadAPIClient\Resource\AbstractResource":private]=>
    array(42) {
      ["id"]=>3,
      [...............
     }`

Thanks in advance! :)

**Comment by jepf** [comment]
Hi @vmendez-es 

when you fetch data, the API client methods always return an array of objects. Only if there was an error, the original object will be returned. In your case this means:

```php
$user_by_email= $client->resource( ResourceType::USER )->search($email_address);
$user_by_email->getValue('id');
```

has to be changed to (please also note the error handling):
```php
$users_by_email= $client->resource( ResourceType::USER )->search($email_address);

// If search() didn't return an array (but the original calling object instead), there was an error.
if ( !is_array($users_by_email) ) {
    $error = $users_by_email->getError();
    # error handling
}

$user_by_email = array_shift($users_by_email);
$user_id = $user_by_email->getValue('id');
# ...
```

**Comment by vmendez-es** [comment]
Thank you very much @jepf!! It worked perfectly!
